pipeline {
    agent any

     triggers {
          pollSCM('H/2 * * * *')
        }

    environment {
        GITLAB_TOKEN = credentials('gitlab_manifest')
        DOCKERHUB_CREDENTIALS = credentials('enami_dockerhub')
        ARGO_CD_REPO = 'https://gitlab.com/enamifatimazahrae/colocation-manifests.git'
        IMAGE_TAG = "v0.${BUILD_NUMBER}"
        APP_REGISTRY = "enamifatimazahrae2001/api-gateway"
        MANIFEST_FILE = "gateway/deployment-api-gateway.yml"
    }

    stages {
        stage('Build Artifact') {
            steps {
                script {
                    dir('api-gateway') {
                        bat "mvn clean install"
                    }
                }
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    dir('api-gateway') {
                        dockerImage = docker.build("${APP_REGISTRY}:${IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'enami_dockerhub',
                                                  usernameVariable: 'DOCKERHUB_CREDENTIALS_USR',
                                                  passwordVariable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                    echo "Docker Username: ${DOCKERHUB_CREDENTIALS_USR}"
                    writeFile file: 'docker_token.txt', text: "${DOCKERHUB_CREDENTIALS_PSW}"

                    bat """
                        docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin < docker_token.txt
                        docker push ${APP_REGISTRY}:${IMAGE_TAG}
                        docker rmi ${APP_REGISTRY}:${IMAGE_TAG} -f
                    """
                }
            }
        }

        stage('Update Argo CD Manifest') {
            steps {
                dir('..') {
                    script {
                        withCredentials([string(credentialsId: 'gitlab_manifest', variable: 'GITLAB_TOKEN')]) {
                            bat """
                                git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/enamifatimazahrae/colocation-manifests.git
                            """

                            dir('colocation-manifests') {
                                bat """
                                    echo "Fichier manifest: ${MANIFEST_FILE}"
                                   powershell "(Get-Content -Path '${MANIFEST_FILE}') -replace 'enamifatimazahrae2001/api-gateway.*', 'enamifatimazahrae2001/api-gateway:${IMAGE_TAG}' | Set-Content -Path '${MANIFEST_FILE}'"
                                    git diff
                                    git add .
                                    git commit -m "Update api-gateway image version to ${IMAGE_TAG}"
                                    git push origin master
                                """
                            }

                            bat "rmdir /S /Q colocation-manifests"
                        }
                    }
                }
            }
        }
    }
}